"""
Playwright test suite for LambdaTest Ecommerce Playground — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from playwright.sync_api import expect

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_searched_for_products_on_ecommerce_playground_lamb(page):
    """SC-001: attempted to add a product to the cart on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    add_btn = page.locator("#button-cart")
    add_btn.wait_for(timeout=15000)
    add_btn.click()
    page.wait_for_timeout(1500)
    cart_indicator = page.locator("#cart button span, #cart-total")
    assert cart_indicator.count() > 0, "Cart indicator not found after adding product"

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_attempted_to_open_the_cart_and_select_a_product_op(page):
    """SC-002: attempted to open a specific product page on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    page.locator("#button-cart").wait_for(timeout=15000)
    page.locator("#button-cart").click()
    page.wait_for_timeout(1500)
    cart_btn = page.locator("#cart > button")
    cart_btn.wait_for(timeout=10000)
    cart_btn.click()
    page.wait_for_timeout(1000)
    cart_items = page.locator("#cart .text-left a")
    cart_items.first.wait_for(timeout=10000)
    assert cart_items.count() > 0, "No items visible in cart dropdown"

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_opened_the_laptops_product_catalog_on_ecommerce_pl(page):
    """SC-003: navigated to the Laptops product catalog on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=18")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    products = page.locator(".product-thumb")
    products.first.wait_for(timeout=15000)
    assert products.count() > 0, "No products visible in the Laptops catalog"

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_attempted_to_filter_components_by_apple_on_ecommer(page):
    """SC-004: applied a manufacturer brand filter on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=25")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    filter_link = page.locator("#column-left .list-group-item").filter(has_text="Apple")
    if filter_link.count() == 0:
        filter_link = page.locator("#column-left a").filter(has_text="Apple")
    filter_link.first.wait_for(timeout=15000)
    filter_link.first.click()
    page.wait_for_load_state("domcontentloaded", timeout=15000)
    assert page.locator("#content").count() > 0, "Content area not visible after applying filter"

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_opened_a_product_detail_page_on_ecommerce_playgrou(page):
    """SC-005: opened a product detail page on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    product_name = page.locator("h1").first
    product_name.wait_for(timeout=15000)
    assert product_name.inner_text().strip() != "", "Product name is empty on detail page"
    price = page.locator(".price-new, h2.price, .price").first
    price.wait_for(timeout=10000)
    assert price.count() > 0, "Product price not visible on detail page"

@pytest.mark.scenario("SC-006")
@pytest.mark.requirement("AC-006")
def test_sc_006_browsed_the_homepage_and_product_listings_on_ecomm(page):
    """SC-006: browsed the homepage and product listings on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    hero = page.locator("#content, .slideshow0, .swiper-wrapper, .carousel-inner").first
    hero.wait_for(timeout=15000)
    assert hero.count() > 0, "Homepage content not visible without login"
    assert page.title().strip() != "", "Page title is empty"

@pytest.mark.scenario("SC-007")
@pytest.mark.requirement("AC-007")
def test_sc_007_searched_for_an_iphone_on_ecommerce_playground_lam(page):
    """SC-007: searched for iphone on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    search_input = page.locator("input[name='search']")
    search_input.wait_for(timeout=15000)
    search_input.fill("iPhone")
    search_input.press("Enter")
    page.wait_for_load_state("domcontentloaded", timeout=20000)
    results = page.locator(".product-thumb")
    results.first.wait_for(timeout=15000)
    assert results.count() > 0, "No search results returned for 'iPhone'"

@pytest.mark.scenario("SC-008")
@pytest.mark.requirement("AC-008")
def test_sc_008_opened_the_account_registration_page_on_ecommerce_(page):
    """SC-008: opened the account registration page on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/register")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    first_name = page.locator("#input-firstname")
    first_name.wait_for(timeout=15000)
    assert first_name.count() > 0, "First name field not found"
    assert page.locator("#input-lastname").count() > 0, "Last name field not found"
    assert page.locator("#input-email").count() > 0, "Email field not found"
    assert page.locator("#input-telephone").count() > 0, "Telephone field not found"
    assert page.locator("#input-password").count() > 0, "Password field not found"

@pytest.mark.scenario("SC-009")
@pytest.mark.requirement("AC-009")
def test_sc_009_attempted_to_log_in_on_ecommerce_playground_lambda(page):
    """SC-009: attempted to log in on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    email_field = page.locator("#input-email")
    email_field.wait_for(timeout=15000)
    assert email_field.count() > 0, "Email field not found on login page"
    assert page.locator("#input-password").count() > 0, "Password field not found"
    login_btn = page.locator("input[value='Login']")
    assert login_btn.count() > 0, "Login button not found"

@pytest.mark.scenario("SC-010")
@pytest.mark.requirement("AC-010")
def test_sc_010_attempted_to_log_in_and_log_out_on_ecommerce_playg(page):
    """SC-010: attempted to log in and log out on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    my_account = page.locator("#top .dropdown-toggle, a:has-text('My account')")
    my_account.first.wait_for(timeout=15000)
    assert my_account.count() > 0, "My Account menu not found in navigation"
    my_account.first.click()
    page.wait_for_timeout(600)
    logout_link = page.locator("a[href*='route=account/logout']")
    assert logout_link.count() > 0, "Logout link not visible in account dropdown"

@pytest.mark.scenario("SC-011")
@pytest.mark.requirement("AC-011")
def test_sc_011_attempted_to_click_the_out_of_stock_purchase_butto(page):
    """SC-011: attempted to click the “Out of Stock” purchase button on ecommerce-playground.lambdatest.io.."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    add_btn = page.locator("#button-cart")
    add_btn.wait_for(timeout=15000)
    add_btn.click()
    page.wait_for_timeout(1500)
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=checkout/cart")
    page.wait_for_load_state("domcontentloaded", timeout=20000)
    remove_btn = page.locator(".btn-danger").first
    remove_btn.wait_for(timeout=15000)
    remove_btn.click()
    page.wait_for_timeout(1500)
    body_text = page.locator("body").inner_text()
    assert "empty" in body_text.lower(), "Cart still has items after remove"

@pytest.mark.scenario("SC-012")
@pytest.mark.requirement("AC-012")
def test_sc_012_attempted_to_add_an_out_of_stock_product_to_the_ca(page):
    """SC-012: attempted to add an out-of-stock product to the cart on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    page.locator("#button-cart").wait_for(timeout=15000)
    page.locator("#button-cart").click()
    page.wait_for_timeout(1500)
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=checkout/cart")
    page.wait_for_load_state("domcontentloaded", timeout=20000)
    qty_input = page.locator("input[name*='quantity']").first
    qty_input.wait_for(timeout=15000)
    initial_total = page.locator(".text-right strong").first.inner_text()
    qty_input.fill("2")
    page.locator(".btn-primary").filter(has_text="Update").first.click()
    page.wait_for_load_state("domcontentloaded", timeout=15000)
    updated_total = page.locator(".text-right strong").first.inner_text()
    assert updated_total != initial_total, "Line total did not recalculate after quantity update"

@pytest.mark.scenario("SC-013")
@pytest.mark.requirement("AC-013")
def test_sc_013_sorted_products_by_price_low_to_high_on_ecommerce_(page):
    """SC-013: sorted products by price low to high on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    sort_select = page.locator("#input-sort")
    sort_select.wait_for(timeout=15000)
    sort_select.select_option(label="Price (Low > High)")
    page.wait_for_load_state("domcontentloaded", timeout=15000)
    products = page.locator(".product-thumb")
    products.first.wait_for(timeout=15000)
    assert products.count() > 0, "No products visible after applying price sort"

@pytest.mark.scenario("SC-014")
@pytest.mark.requirement("AC-014")
def test_sc_014_added_a_product_to_the_wish_list_on_ecommerce_play(page):
    """SC-014: added a product to the wish list on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=40")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    product_name = page.locator("h1").first
    product_name.wait_for(timeout=15000)
    assert product_name.inner_text().strip() != "", "Product name not found"
    wishlist_btn = page.locator(
        "button[data-original-title*='Wish'], .btn-wishlist, [href*='wishlist']"
    ).first
    assert wishlist_btn.count() > 0, "Wishlist button not found on product page"

@pytest.mark.scenario("SC-015")
@pytest.mark.requirement("AC-015")
def test_sc_015_attempted_to_add_the_htc_touch_hd_product_to_the_c(page):
    """SC-015: attempted to add the HTC Touch HD product to the cart on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    page.locator("#button-cart").wait_for(timeout=15000)
    page.locator("#button-cart").click()
    page.wait_for_timeout(1500)
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=checkout/checkout")
    page.wait_for_load_state("domcontentloaded", timeout=20000)
    guest_option = page.locator("#account-guest")
    login_page_email = page.locator("#input-email")
    has_guest = guest_option.count() > 0
    has_checkout = login_page_email.count() > 0
    assert has_guest or has_checkout, "Guest checkout option not available"
