#!/usr/bin/env python3
"""
Agentic STLC Orchestrator — Stages 2-7.
Fully deterministic: no LLM required.
"""
import asyncio
import json
import os
import py_compile
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
from mcp import ClientSession
from mcp.client.sse import sse_client

sys.path.insert(0, str(Path(__file__).parent))
from stage_utils import print_stage_header, print_stage_result

# ── Runtime config ─────────────────────────────────────────────────────────
MCP_URL           = "https://mcp.lambdatest.com/mcp"
LT_API_BASE       = "https://api.lambdatest.com/automation/api/v1"
LT_USERNAME       = os.environ.get("LT_USERNAME", "")
LT_ACCESS_KEY     = os.environ.get("LT_ACCESS_KEY", "")
FULL_RUN          = os.environ.get("FULL_RUN", "true").lower() == "true"
TARGET_URL        = os.environ.get("TARGET_URL", "https://ecommerce-playground.lambdatest.io/")
TODAY             = datetime.now(timezone.utc).date().isoformat()
RUN_NUMBER        = os.environ.get("GITHUB_RUN_NUMBER", "")
BUILD_NAME        = (
    f"Agentic STLC #{RUN_NUMBER} | {TODAY}" if RUN_NUMBER
    else f"Agentic STLC | {TODAY}"
)

JOB_ID_RE = re.compile(r"jobId=([\w-]+)")
_TERMINAL_HE_STATUSES = {"completed", "passed", "failed", "error", "aborted", "cancelled"}

# Extended patterns to extract job ID from varied HE CLI output formats
_JOB_ID_PATTERNS = [
    re.compile(r"jobId=([\w-]+)"),
    re.compile(r"job[_\s-]?id[:\s=]+([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})", re.IGNORECASE),
    re.compile(r"hyperexecute/task\?jobId=([\w-]+)", re.IGNORECASE),
    re.compile(r"Job\s+(?:ID|Id|id)[:\s]+([0-9a-f]{8}-[0-9a-f]{4}-[\w-]+)", re.IGNORECASE),
]

# Enterprise-normalized status map: raw HE API value → deterministic label
_HE_STATUS_NORMALIZE: dict[str, str] = {
    "completed":  "PASSED",
    "passed":     "PASSED",
    "failed":     "FAILED",
    "error":      "INFRA_FAILURE",
    "aborted":    "CANCELLED",
    "cancelled":  "CANCELLED",
    "running":    "RUNNING",
    "initiated":  "RUNNING",
    "queued":     "RUNNING",
    "unknown":    "",          # resolved dynamically from tasks
    "":           "",
}


def _extract_job_id(text: str) -> str:
    """Try multiple regex patterns to extract HE job ID from CLI output."""
    for pattern in _JOB_ID_PATTERNS:
        m = pattern.search(text)
        if m:
            return m.group(1)
    return ""


def _derive_status_from_tasks(he_tasks: list) -> str:
    """
    When the HE job API is unreachable, derive a terminal status from
    individual task results.  Returns a raw HE-compatible status string
    so the rest of the pipeline remains unchanged.
    """
    if not he_tasks:
        return ""
    statuses = [t.get("status", "") for t in he_tasks]
    terminal = [s for s in statuses if s in ("passed", "failed")]
    if not terminal:
        return ""
    if all(s == "passed" for s in terminal):
        return "completed"
    return "failed"


def _normalize_he_status(raw_status: str, he_tasks: list) -> str:
    """
    Map a raw HE status (or a task-derived status) to an enterprise-grade
    deterministic label.  Never returns 'unknown'.
    """
    normalized = _HE_STATUS_NORMALIZE.get((raw_status or "").lower())
    if normalized:
        return normalized
    # Derive from task results when raw status is ambiguous/empty
    if he_tasks:
        task_statuses = [t.get("status", "") for t in he_tasks]
        passed = sum(1 for s in task_statuses if s == "passed")
        failed = sum(1 for s in task_statuses if s == "failed")
        total  = passed + failed
        if total == 0:
            return "NOT_EXECUTED"
        if failed == 0:
            return "PASSED"
        if passed == 0:
            return "FAILED"
        return "PARTIAL"
    return "NOT_EXECUTED" if not raw_status else "INFRA_FAILURE"

# ── Deterministic test generation ──────────────────────────────────────────
def _derive_fn_name(sc_id: str, title: str) -> str:
    """Derive a stable pytest function name from scenario ID + title."""
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:50]
    return f"test_{sc_id.lower().replace('-', '_')}_{slug}"

TEST_HEADER = '''\
"""
Playwright test suite for LambdaTest Ecommerce Playground — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from playwright.sync_api import expect

'''

# Product ID 47 (HP LP3065) is in stock with no required options — safe for Add to Cart tests.
# product_id=28 (HTC Touch HD) was retired here on 2026-05-15 after going out of stock on the AUT.
_ECOM = "https://ecommerce-playground.lambdatest.io"

def _ec(path: str) -> str:
    return f'"{_ECOM}{path}"'


PLAYWRIGHT_BODIES = {
    # AC-001: Add a product to the cart from the product detail page and see cart count update
    "SC-001": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    add_btn = page.locator("#button-cart")\n'
        '    add_btn.wait_for(timeout=15000)\n'
        '    cart_btn = page.locator("#cart > button").first\n'
        '    cart_btn.wait_for(timeout=10000)\n'
        '    before = cart_btn.inner_text().strip()\n'
        '    add_btn.click()\n'
        '    expect(cart_btn).not_to_have_text(before, timeout=10000)\n'
        '    after = cart_btn.inner_text().strip()\n'
        '    assert after != before, f"Cart text did not change after Add to Cart (before={before!r}, after={after!r})"\n'
        '    assert "0 item" not in after, f"Cart still shows 0 items after Add to Cart: {after!r}"'
    ),

    # AC-002: Open the cart and see the list of added items with names and prices
    "SC-002": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    page.locator("#button-cart").wait_for(timeout=15000)\n'
        '    cart_btn = page.locator("#cart > button").first\n'
        '    cart_btn.wait_for(timeout=10000)\n'
        '    before = cart_btn.inner_text().strip()\n'
        '    page.locator("#button-cart").click()\n'
        '    expect(cart_btn).not_to_have_text(before, timeout=10000)\n'
        '    cart_btn.click()\n'
        '    cart_items = page.locator("#cart .text-left a, #cart table img, #cart .table img")\n'
        '    cart_items.first.wait_for(timeout=10000)\n'
        '    assert cart_items.count() > 0, "No items visible in cart dropdown after add"'
    ),

    # AC-003: Navigate to the product catalog and see a list of products
    "SC-003": (
        '    page.goto(' + _ec('/index.php?route=product/category&path=18') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    products = page.locator(".product-thumb")\n'
        '    products.first.wait_for(timeout=15000)\n'
        '    assert products.count() > 0, "No products visible in the Laptops catalog"'
    ),

    # AC-004: Apply a brand filter from the sidebar to narrow product results
    "SC-004": (
        '    page.goto(' + _ec('/index.php?route=product/category&path=25') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    filter_link = page.locator("#column-left .list-group-item").filter(has_text="Apple")\n'
        '    if filter_link.count() == 0:\n'
        '        filter_link = page.locator("#column-left a").filter(has_text="Apple")\n'
        '    filter_link.first.wait_for(timeout=15000)\n'
        '    filter_link.first.click()\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=15000)\n'
        '    assert page.locator("#content").count() > 0, "Content area not visible after applying filter"'
    ),

    # AC-005: Click a product to open its detail page and see the name and price
    "SC-005": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    product_name = page.locator("h1").first\n'
        '    product_name.wait_for(timeout=15000)\n'
        '    assert product_name.inner_text().strip() != "", "Product name is empty on detail page"\n'
        '    price = page.locator(".price-new, h2.price, .price").first\n'
        '    price.wait_for(timeout=10000)\n'
        '    assert price.count() > 0, "Product price not visible on detail page"'
    ),

    # AC-006: Browse products and the homepage without logging in
    "SC-006": (
        '    page.goto(' + _ec('/') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    hero = page.locator("#content, .slideshow0, .swiper-wrapper, .carousel-inner").first\n'
        '    hero.wait_for(timeout=15000)\n'
        '    assert hero.count() > 0, "Homepage content not visible without login"\n'
        '    assert page.title().strip() != "", "Page title is empty"'
    ),

    # AC-007: Search for a product by name and see relevant results
    "SC-007": (
        '    page.goto(' + _ec('/') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    search_input = page.locator("input[name=\'search\']")\n'
        '    search_input.wait_for(timeout=15000)\n'
        '    search_input.fill("iPhone")\n'
        '    search_input.press("Enter")\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=20000)\n'
        '    results = page.locator(".product-thumb")\n'
        '    results.first.wait_for(timeout=15000)\n'
        '    assert results.count() > 0, "No search results returned for \'iPhone\'"'
    ),

    # AC-008: Register a new account — verify the registration form and all required fields exist
    "SC-008": (
        '    page.goto(' + _ec('/index.php?route=account/register') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    first_name = page.locator("#input-firstname")\n'
        '    first_name.wait_for(timeout=15000)\n'
        '    assert first_name.count() > 0, "First name field not found"\n'
        '    assert page.locator("#input-lastname").count() > 0, "Last name field not found"\n'
        '    assert page.locator("#input-email").count() > 0, "Email field not found"\n'
        '    assert page.locator("#input-telephone").count() > 0, "Telephone field not found"\n'
        '    assert page.locator("#input-password").count() > 0, "Password field not found"'
    ),

    # AC-009: Log in — verify login form fields and login button are present and functional
    "SC-009": (
        '    page.goto(' + _ec('/index.php?route=account/login') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    email_field = page.locator("#input-email")\n'
        '    email_field.wait_for(timeout=15000)\n'
        '    assert email_field.count() > 0, "Email field not found on login page"\n'
        '    assert page.locator("#input-password").count() > 0, "Password field not found"\n'
        '    login_btn = page.locator("input[value=\'Login\']")\n'
        '    assert login_btn.count() > 0, "Login button not found"'
    ),

    # AC-010: Log out — verify My Account dropdown and Logout link are accessible
    "SC-010": (
        '    page.goto(' + _ec('/') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    my_account = page.locator("#top .dropdown-toggle, a:has-text(\'My account\')")\n'
        '    my_account.first.wait_for(timeout=15000)\n'
        '    assert my_account.count() > 0, "My Account menu not found in navigation"\n'
        '    my_account.first.click()\n'
        '    page.wait_for_timeout(600)\n'
        '    logout_link = page.locator("a[href*=\'route=account/logout\']")\n'
        '    assert logout_link.count() > 0, "Logout link not visible in account dropdown"'
    ),

    # AC-011: Remove item from cart — add product_id=47 (no required options), navigate to cart, remove it
    "SC-011": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    add_btn = page.locator("#button-cart")\n'
        '    add_btn.wait_for(timeout=15000)\n'
        '    cart_btn = page.locator("#cart > button").first\n'
        '    cart_btn.wait_for(timeout=10000)\n'
        '    before = cart_btn.inner_text().strip()\n'
        '    add_btn.click()\n'
        '    expect(cart_btn).not_to_have_text(before, timeout=10000)\n'
        '    page.goto(' + _ec('/index.php?route=checkout/cart') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=20000)\n'
        '    remove_btn = page.locator(".btn-danger, button[aria-label*=\'Remove\'], i.fa-times").first\n'
        '    remove_btn.wait_for(timeout=15000)\n'
        '    remove_btn.click()\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=15000)\n'
        '    page.wait_for_timeout(1500)\n'
        '    body_text = page.locator("body").inner_text()\n'
        '    assert "empty" in body_text.lower(), f"Cart not empty after remove. body excerpt: {body_text[:300]!r}"'
    ),

    # AC-012: Update cart quantity — add product_id=47, navigate to cart, update qty to 2, verify total changes
    "SC-012": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    page.locator("#button-cart").wait_for(timeout=15000)\n'
        '    cart_btn = page.locator("#cart > button").first\n'
        '    cart_btn.wait_for(timeout=10000)\n'
        '    before_add = cart_btn.inner_text().strip()\n'
        '    page.locator("#button-cart").click()\n'
        '    expect(cart_btn).not_to_have_text(before_add, timeout=10000)\n'
        '    page.goto(' + _ec('/index.php?route=checkout/cart') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=20000)\n'
        '    qty_input = page.locator("input[name*=\'quantity\']").first\n'
        '    qty_input.wait_for(timeout=15000)\n'
        '    initial_total = page.locator(".text-right strong, td.text-right").first.inner_text().strip()\n'
        '    qty_input.fill("2")\n'
        '    update_btn = page.locator("button[data-original-title*=\'Update\'], .btn-primary, button.fa-refresh").first\n'
        '    update_btn.click()\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=15000)\n'
        '    page.wait_for_timeout(1500)\n'
        '    updated_total = page.locator(".text-right strong, td.text-right").first.inner_text().strip()\n'
        '    assert updated_total != initial_total, f"Line total did not recalculate (before={initial_total!r}, after={updated_total!r})"'
    ),

    # AC-013: Sort products by price low-to-high and verify order changes
    "SC-013": (
        '    page.goto(' + _ec('/index.php?route=product/category&path=20') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    sort_select = page.locator("#input-sort")\n'
        '    sort_select.wait_for(timeout=15000)\n'
        '    sort_select.select_option(label="Price (Low > High)")\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=15000)\n'
        '    products = page.locator(".product-thumb")\n'
        '    products.first.wait_for(timeout=15000)\n'
        '    assert products.count() > 0, "No products visible after applying price sort"'
    ),

    # AC-014: Wishlist — verify the Add to Wish List button exists on a product detail page
    "SC-014": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=40') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    product_name = page.locator("h1").first\n'
        '    product_name.wait_for(timeout=15000)\n'
        '    assert product_name.inner_text().strip() != "", "Product name not found"\n'
        '    wishlist_btn = page.locator(\n'
        '        "button[data-original-title*=\'Wish\'], .btn-wishlist, [href*=\'wishlist\']"\n'
        '    ).first\n'
        '    assert wishlist_btn.count() > 0, "Wishlist button not found on product page"'
    ),

    # AC-015: Guest checkout — add to cart then verify guest checkout option is available at checkout
    "SC-015": (
        '    page.goto(' + _ec('/index.php?route=product/product&product_id=47') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=30000)\n'
        '    page.locator("#button-cart").wait_for(timeout=15000)\n'
        '    page.locator("#button-cart").click()\n'
        '    page.wait_for_timeout(1500)\n'
        '    page.goto(' + _ec('/index.php?route=checkout/checkout') + ')\n'
        '    page.wait_for_load_state("domcontentloaded", timeout=20000)\n'
        '    guest_option = page.locator("#account-guest")\n'
        '    login_page_email = page.locator("#input-email")\n'
        '    has_guest = guest_option.count() > 0\n'
        '    has_checkout = login_page_email.count() > 0\n'
        '    assert has_guest or has_checkout, "Guest checkout option not available"'
    ),
}

_FALLBACK_BODY = '''\
    page.goto("{url}")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    assert page.title().strip() != "", "Page failed to load"'''


def _build_test_function(scenario: dict) -> str:
    sc_id   = scenario["id"]
    fn_name = scenario.get("function_name") or _derive_fn_name(sc_id, scenario.get("title", sc_id))
    title   = scenario.get("title", sc_id).replace('"', "'")
    url     = scenario.get("kane_url", TARGET_URL)
    body    = PLAYWRIGHT_BODIES.get(sc_id, _FALLBACK_BODY).format(url=url)
    req_id  = scenario.get("requirement_id", "AC-000")
    return (
        f'@pytest.mark.scenario("{sc_id}")\n'
        f'@pytest.mark.requirement("{req_id}")\n'
        f'def {fn_name}(page):\n'
        f'    """{sc_id}: {title}."""\n'
        f'{body}\n'
    )


# ── Stage 2: Sync scenarios (deterministic diff) ───────────────────────────
def sync_scenarios(requirements: list, existing: list) -> list:
    existing_by_req = {s["requirement_id"]: s for s in existing}
    current_req_ids = {r["id"] for r in requirements}

    max_num = 0
    for sc in existing:
        m = re.match(r"SC-(\d+)", sc.get("id", ""))
        if m:
            max_num = max(max_num, int(m.group(1)))
    next_num = max_num + 1

    result = []
    for req in requirements:
        existing_sc = existing_by_req.get(req["id"])
        if existing_sc is None:
            sc_id  = f"SC-{next_num:03d}"
            tc_id  = f"TC-{next_num:03d}"
            next_num += 1
            status = "new"
        else:
            sc_id  = existing_sc["id"]
            tc_id  = existing_sc.get("test_case_id", sc_id.replace("SC-", "TC-"))
            status = (
                "updated" if existing_sc.get("source_description") != req["description"]
                else "active"
            )

        title = req.get("kane_one_liner") or req.get("title", req["id"])
        fn_name = (
            existing_sc.get("function_name")
            if existing_sc
            else _derive_fn_name(sc_id, title)
        )
        result.append({
            "id":                 sc_id,
            "test_case_id":       tc_id,
            "requirement_id":     req["id"],
            "title":              title,
            "function_name":      fn_name,
            "status":             status,
            "source_description": req["description"],
            "steps":              req.get("kane_steps") or [
                f"Navigate to {TARGET_URL}", "Verify the acceptance criterion"
            ],
            "expected_result":    req.get("kane_summary") or req["description"],
            "kane_url":           TARGET_URL,
            "last_verified":      TODAY,
        })

    # Preserve deprecated entries for removed requirements
    for sc in existing:
        if sc["requirement_id"] not in current_req_ids:
            deprecated = {**sc, "status": "deprecated"}
            if "function_name" not in deprecated:
                deprecated["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
            result.append(deprecated)

    return result


# ── Stage 3: Generate tests ─────────────────────────────────────────────────
def generate_tests(scenarios: list) -> None:
    active = [s for s in scenarios if s["status"] != "deprecated"]
    lines  = [TEST_HEADER.rstrip(), ""]
    objectives = []
    for sc in active:
        lines.append(_build_test_function(sc).rstrip())
        lines.append("")
        objectives.append({
            "scenario_id": sc["id"],
            "test_case_id": sc.get("test_case_id", ""),
            "objective": sc.get("title", sc["id"]),
        })

    out = Path("tests/playwright/test_powerapps.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    # Ensure function_name is set on each active scenario (for downstream scripts)
    for sc in active:
        if not sc.get("function_name"):
            sc["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))

    Path("kane").mkdir(exist_ok=True)
    Path("kane/objectives.json").write_text(json.dumps(objectives, indent=2), encoding="utf-8")
    print(f"[generate_tests] wrote {len(active)} test(s)")


def validate_generated_tests(test_file: str = "tests/playwright/test_powerapps.py") -> bool:
    """Validate generated Playwright test file has valid Python syntax."""
    try:
        py_compile.compile(test_file, doraise=True)
        print(f"[validate_tests] {test_file} — syntax OK")
        return True
    except py_compile.PyCompileError as e:
        print(f"[validate_tests] SYNTAX ERROR in {test_file}: {e}", file=sys.stderr)
        return False


# ── Stage 4: Write test selection ──────────────────────────────────────────
def write_test_selection(scenarios: list) -> list:
    if FULL_RUN:
        selected = [s for s in scenarios if s["status"] != "deprecated"]
    else:
        selected = [s for s in scenarios if s["status"] in ("new", "updated")]

    lines = []
    for sc in selected:
        fn = sc.get("function_name") or _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
        lines.append(f"tests/playwright/test_powerapps.py::{fn}")

    Path("reports").mkdir(exist_ok=True)
    Path("reports/pytest_selection.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    run_type = "full" if FULL_RUN else "incremental"
    manifest = {
        "selected_scenarios": [s["id"] for s in selected],
        "run_type": run_type,
    }
    Path("reports/test_execution_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"[test_selection] {len(lines)} test(s) — {run_type} run")
    return selected


def validate_test_selection(selection_file: str = "reports/pytest_selection.txt") -> bool:
    """Validate test selection file exists and is non-empty."""
    p = Path(selection_file)
    if not p.exists():
        print(f"[validate_selection] {selection_file} does not exist", file=sys.stderr)
        return False
    lines = [l.strip() for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]
    if not lines:
        print(f"[validate_selection] {selection_file} is empty — no tests to run", file=sys.stderr)
        return False
    print(f"[validate_selection] {len(lines)} test node(s) queued")
    return True


# ── Stage 5: Run HyperExecute ──────────────────────────────────────────────
def run_hyperexecute() -> str:
    # On Windows the binary ships as hyperexecute.exe; on Linux it has no extension.
    cli_name = "hyperexecute.exe" if sys.platform == "win32" else "hyperexecute"
    cwd = Path(".").resolve()
    cli_path = cwd / cli_name
    cli = str(cli_path) if sys.platform == "win32" else f"./{cli_name}"
    print(f"[hyperexecute] cwd={cwd}  platform={sys.platform}  binary_exists={cli_path.exists()}")

    if not cli_path.exists():
        print("[hyperexecute] binary not found — skipping HyperExecute stage")
        return ""

    if not LT_USERNAME or not LT_ACCESS_KEY:
        print("[hyperexecute] LT credentials missing — skipping HyperExecute stage")
        return ""

    # Validate test selection before submitting
    if not validate_test_selection():
        print("[hyperexecute] aborting — no tests to run")
        return ""

    sel_path = Path("reports/pytest_selection.txt")
    lines = [l.strip() for l in sel_path.read_text().splitlines() if l.strip()]
    print(f"[hyperexecute] submitting {len(lines)} test(s):")
    for line in lines:
        print(f"  {line}")

    cmd = [cli, "--user", LT_USERNAME, "--key", LT_ACCESS_KEY, "--config", "hyperexecute.yaml"]
    print(f"[hyperexecute] starting — cmd: {' '.join(cmd[:3])} ...")
    t0 = time.monotonic()
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=1800, encoding="utf-8", errors="replace")
    elapsed = round(time.monotonic() - t0, 1)
    combined = result.stdout + result.stderr

    Path("reports").mkdir(exist_ok=True)
    Path("reports/hyperexecute-cli.log").write_text(combined, encoding="utf-8")
    print(f"[hyperexecute] exit_code={result.returncode}  duration={elapsed}s  output_lines={len(combined.splitlines())}")
    if combined.strip():
        for line in combined.splitlines()[:30]:
            print(f"  {line}")

    job_id = _extract_job_id(combined)
    print(f"[hyperexecute] job_id={job_id!r}  (extracted via multi-pattern parser)")
    if not job_id:
        print("[hyperexecute] WARNING: could not extract job_id from CLI output — status resolution will use task-derived fallback")
    return job_id


# ── Stage 6: Fetch results ────────────────────────────────────────────────

# MCP responses wrap JSON in a markdown code block: ```json\n{...}\n```
_JSON_BLOCK_RE = re.compile(r"```json\s*([\s\S]*?)\s*```")


def _parse_mcp_text(text: str) -> object:
    """Parse JSON from an MCP response, stripping any markdown code fence."""
    m = _JSON_BLOCK_RE.search(text)
    candidate = m.group(1) if m else text.strip()
    return json.loads(candidate)


def _parse_session(s: dict, source: str) -> dict:
    """Normalise a session record from either the HE API or the Automation API."""
    raw_name = (
        s.get("scenario_name") or s.get("name") or s.get("session_name", "")
    )
    # conftest names sessions "SC-001 | TC-001 | test_sc_001_..." — extract fn name
    parts   = [p.strip() for p in raw_name.split("|")]
    fn_name = parts[-1] if len(parts) > 1 else raw_name
    test_id = s.get("testID") or s.get("test_id") or s.get("session_id", "")
    task_id = s.get("taskID") or s.get("task_id", "")
    status_raw = s.get("status") or s.get("status_ind", "unknown")
    status = "passed" if status_raw in ("passed", "pass", "completed") else (
        "failed" if status_raw in ("failed", "fail", "error") else status_raw
    )
    link = (
        f"https://automation.lambdatest.com/test?testID={test_id}"
        if test_id else ""
    )
    print(f"  [{source}] {fn_name!r} → {status}  testID={test_id}")
    return {"name": fn_name, "task_id": task_id, "status": status, "session_link": link}


async def _fetch_he_sessions_api(client: httpx.AsyncClient, job_id: str) -> list:
    """Try HyperExecute /v2.0/job/{id}/sessions endpoint."""
    tasks = []
    cursor = None
    page = 0
    while True:
        params: dict = {"limit": 20}
        if cursor:
            params["cursor"] = cursor
        resp = await client.get(
            f"https://api.hyperexecute.cloud/v2.0/job/{job_id}/sessions",
            params=params,
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[he_sessions_api] {resp.status_code} — {resp.text[:200]}")
            return []
        data = resp.json()
        page_sessions = data.get("data", [])
        print(f"[he_sessions_api] page {page}: {len(page_sessions)} session(s)")
        tasks.extend(_parse_session(s, "he_api") for s in page_sessions)
        metadata = data.get("metadata", {})
        if not metadata.get("hasmore"):
            break
        cursor = metadata.get("cursor")
        if not cursor:
            break
        page += 1
    return tasks


async def _fetch_automation_sessions_by_build(client: httpx.AsyncClient, build_name: str) -> list:
    """
    Fall back to LambdaTest Automation API: find the build by name and return its sessions.
    conftest.py sets build=BUILD_NAME, so the build should be searchable by that exact name.
    """
    build_id = None
    for search in (build_name, "Agentic STLC"):
        resp = await client.get(
            f"{LT_API_BASE}/builds",
            params={"s": search, "limit": 5, "sort": "desc"},
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[automation] builds search {resp.status_code}")
            continue
        builds = resp.json().get("data", [])
        print(f"[automation] {len(builds)} build(s) for search={search!r}")
        for b in builds:
            name = b.get("name", "")
            if build_name in name or search == "Agentic STLC":
                build_id = b.get("build_id")
                print(f"[automation] matched build_id={build_id!r} name={name!r}")
                break
        if build_id:
            break

    if not build_id:
        print("[automation] no matching build found")
        return []

    resp = await client.get(
        f"{LT_API_BASE}/sessions",
        params={"build_id": build_id, "limit": 50},
        auth=(LT_USERNAME, LT_ACCESS_KEY),
    )
    if resp.status_code != 200:
        print(f"[automation] sessions {resp.status_code}")
        return []
    sessions = resp.json().get("data", [])
    print(f"[automation] {len(sessions)} session(s) for build_id={build_id}")
    return [_parse_session(s, "automation") for s in sessions]


async def _fetch_he_job_status_rest(client: httpx.AsyncClient, job_id: str) -> dict:
    """
    Direct HyperExecute REST API call to retrieve job status.
    Used as a fallback when MCP is unreachable.
    Returns a job_inner dict compatible with _write_api_details expectations.
    """
    if not job_id or not LT_USERNAME or not LT_ACCESS_KEY:
        return {}
    try:
        resp = await client.get(
            f"https://api.hyperexecute.cloud/v2.0/job/{job_id}",
            auth=(LT_USERNAME, LT_ACCESS_KEY),
            timeout=15,
        )
        if resp.status_code == 200:
            data = resp.json()
            job_inner = data.get("data") or data.get("jobInfo") or data
            status = job_inner.get("status", "")
            print(f"[he_rest] job status from REST API: {status!r}  job_id={job_id}")
            return job_inner
        print(f"[he_rest] REST API returned HTTP {resp.status_code} for job_id={job_id}")
    except Exception as exc:
        print(f"[he_rest] REST API call failed: {exc}")
    return {}


async def _fetch_he_sessions(job_id: str) -> list:
    """
    Fetch per-test session results.
    Strategy 1: HyperExecute /v2.0/job/{id}/sessions  (direct, by job_id)
    Strategy 2: LambdaTest Automation API /builds + /sessions (by build name)
    """
    async with httpx.AsyncClient(timeout=30) as client:
        tasks = []
        if job_id:
            try:
                tasks = await _fetch_he_sessions_api(client, job_id)
            except Exception as exc:
                print(f"[he_sessions_api] error: {exc}")

        if not tasks:
            print(f"[he_sessions] HE API returned 0 — trying Automation API (build={BUILD_NAME!r})")
            try:
                tasks = await _fetch_automation_sessions_by_build(client, BUILD_NAME)
            except Exception as exc:
                print(f"[automation] error: {exc}")

    print(f"[he_sessions] final: {len(tasks)} session(s)")
    return tasks


async def fetch_and_save_mcp_results(job_id: str) -> None:
    if not job_id:
        print("[mcp] no job_id — writing empty api_details.json")
        _write_api_details({}, [], job_id)
        return

    mcp_url_auth = f"{MCP_URL}?username={LT_USERNAME}&accessKey={LT_ACCESS_KEY}"
    headers = {"x-lt-username": LT_USERNAME, "x-lt-access-key": LT_ACCESS_KEY}

    try:
        async with sse_client(mcp_url_auth, headers=headers) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()

                # Poll until job reaches a terminal status (max 15 min)
                job_data: dict = {}
                job_inner: dict = {}
                for attempt in range(30):
                    raw = await session.call_tool("getHyperExecuteJobInfo", {"jobId": job_id})
                    text = raw.content[0].text if raw.content else "{}"
                    try:
                        job_data  = _parse_mcp_text(text)
                        job_inner = job_data.get("jobInfo") or job_data.get("data") or job_data
                    except (json.JSONDecodeError, AttributeError):
                        job_inner = {}
                    status = job_inner.get("status", "unknown")
                    print(f"[mcp] attempt {attempt+1}/30 — job status: {status}")
                    if status in _TERMINAL_HE_STATUSES:
                        print(f"[mcp] terminal status reached: {status}")
                        break
                    if status not in ("running", "initiated", "queued"):
                        print(f"[mcp] unknown status '{status}' — stopping poll")
                        break
                    await asyncio.sleep(30)

                he_tasks = await _fetch_he_sessions(job_id)
                _write_api_details(job_inner, he_tasks, job_id)

    except Exception as exc:
        print(f"[mcp] connection failed: {exc} — falling back to HE REST API + sessions API")
        async with httpx.AsyncClient(timeout=30) as _fb_client:
            job_inner_fb = await _fetch_he_job_status_rest(_fb_client, job_id) if job_id else {}
        he_tasks = await _fetch_he_sessions(job_id)
        _write_api_details(job_inner_fb, he_tasks, job_id)


def _write_api_details(job_inner: dict, he_tasks: list, job_id: str) -> None:
    raw_status = (job_inner.get("status") or "").strip()

    # When the job API is unavailable or returns "unknown", derive from task results
    # so the report never shows an unresolvable status.
    if not raw_status or raw_status == "unknown":
        derived = _derive_status_from_tasks(he_tasks)
        if derived:
            print(f"[api_details] raw status={raw_status!r} — derived '{derived}' from {len(he_tasks)} task result(s)")
            raw_status = derived
            parser_status = "derived_from_tasks"
        else:
            parser_status = "not_executed" if not job_id else "mcp_unavailable"
    else:
        parser_status = "api_ok"

    normalized_status = _normalize_he_status(raw_status, he_tasks)

    task_pass  = sum(1 for t in he_tasks if t.get("status") == "passed")
    task_fail  = sum(1 for t in he_tasks if t.get("status") == "failed")
    task_other = len(he_tasks) - task_pass - task_fail

    he_summary = {
        "job_id":                job_inner.get("jobId") or job_id,
        "job_link":              job_inner.get("jobLink") or (
            f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}" if job_id else ""
        ),
        "status":                raw_status or "NOT_EXECUTED",
        "normalized_status":     normalized_status,
        "parser_status":         parser_status,
        "total_tasks":           job_inner.get("totalTasks") or len(he_tasks),
        "task_pass_count":       task_pass,
        "task_fail_count":       task_fail,
        "task_other_count":      task_other,
        "selenium_reports_link": job_inner.get("seleniumReportsLink", ""),
        "runtime_logs_link":     job_inner.get("runtimeLogsLink", ""),
    }
    api_details = {"he_summary": he_summary, "he_tasks": he_tasks, "kane_sessions": []}
    Path("reports").mkdir(exist_ok=True)
    Path("reports/api_details.json").write_text(
        json.dumps(api_details, indent=2), encoding="utf-8"
    )
    print(
        f"[api_details] saved {len(he_tasks)} task(s) — "
        f"raw={raw_status!r}  normalized={normalized_status}  parser={parser_status}"
        f"  pass={task_pass} fail={task_fail}"
    )


# ── Stage 7: Release recommendation (threshold-based) ─────────────────────
def _dedup_tasks(he_tasks: list) -> list:
    """Deduplicate by test name, keeping the first occurrence (LT API returns newest first)."""
    seen: dict = {}
    for t in he_tasks:
        key = t.get("name") or t.get("task_id", "")
        seen.setdefault(key, t)
    return list(seen.values())


def write_recommendation(he_tasks: list, requirements_total: int) -> None:
    he_tasks = _dedup_tasks(he_tasks)
    total  = len(he_tasks)
    passed = sum(1 for t in he_tasks if t["status"] == "passed")
    failed = total - passed
    pass_rate = round(passed / total * 100, 1) if total > 0 else 0.0

    if total == 0:
        verdict = "YELLOW"
        rec = "Test results not yet available — manual review required before release."
    elif pass_rate >= 80:
        verdict = "GREEN"
        rec = f"Approve release — {passed}/{total} tests passed ({pass_rate}%)."
    elif pass_rate >= 60:
        verdict = "YELLOW"
        rec = f"Conditional release — {failed} test(s) failed. Review failures before proceeding."
    else:
        verdict = "RED"
        rec = f"Block release — pass rate is {pass_rate}% ({failed} failed). Investigate failures."

    failing_lines = (
        "- None" if failed == 0
        else "\n".join(
            f"- {t['name'] or t['task_id']}"
            for t in he_tasks if t["status"] != "passed"
        )
    )

    content = f"""# QA Release Recommendation
**Verdict:** {verdict}
## Summary
- Requirements covered: {requirements_total}/{requirements_total}
- Scenarios executed: {total}
- Pass rate: {pass_rate}% ({passed} passed, {failed} failed)
## Failing Scenarios
{failing_lines}
## Recommendation
{rec}
"""
    Path("reports/release_recommendation.md").write_text(content, encoding="utf-8")
    print(f"[recommendation] Verdict: {verdict}  pass_rate={pass_rate}%")


# ── Post-pipeline: deterministic CI report scripts ─────────────────────────
# Critical scripts must all succeed — pipeline exits 1 if any fail.
# Order matters: normalize → traceability → coverage → gates → rca → summary
_CRITICAL_SCRIPTS = [
    "ci/normalize_artifacts.py",
    # Stage 2b — confidence scoring runs before traceability so its outputs
    # (high_risk_requirements.json, scenario-confidence-report.json) are
    # available to release_recommendation and write_github_summary.
    "ci/scenario_confidence.py",
    "ci/build_traceability.py",
    "ci/release_recommendation.py",
    "ci/coverage_analysis.py",
    "ci/write_github_summary.py",
]
# Advisory scripts log warnings but never block the pipeline.
# Order matters: fetch_rca must run before failure_intelligence (reads rca_report.json),
# and failure_intelligence must run before self_healing (reads failure_intelligence.json).
_ADVISORY_SCRIPTS = [
    # Stage 0 — Agentic Release Notes diff (preview only by default).
    # Runs unconditionally; if there's no release_notes/*.md it exits 1
    # which the advisory chain logs as a warning and moves on.
    "ci/release_diff.py",
    "ci/impact_analysis.py",
    "ci/quality_gates.py",
    "ci/fetch_rca.py",
    "ci/failure_intelligence.py",
    "ci/self_healing.py",
    "ci/validate_report.py",
    "ci/pipeline_metrics.py",
]


def post_pipeline() -> None:
    """Run post-pipeline scripts. Exits non-zero if any critical script fails."""
    failed_critical = []

    for script in _CRITICAL_SCRIPTS:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout.strip())
        if result.returncode != 0:
            print(f"[ERROR] Critical script failed: {script} (exit {result.returncode})", file=sys.stderr)
            if result.stderr:
                print(result.stderr[:800], file=sys.stderr)
            failed_critical.append(script)
        else:
            print(f"[post-pipeline] {script} ok")

    for script in _ADVISORY_SCRIPTS:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout.strip())
        if result.returncode != 0:
            print(f"[warn] Advisory script failed: {script} (exit {result.returncode})")
            if result.stderr:
                print(result.stderr[:400])
        else:
            print(f"[post-pipeline] {script} ok")

    if failed_critical:
        print(
            f"\n[PIPELINE] {len(failed_critical)} critical script(s) failed: "
            + ", ".join(failed_critical),
            file=sys.stderr,
        )
        sys.exit(1)


# ── Main ────────────────────────────────────────────────────────────────────
async def main() -> None:
    Path("reports").mkdir(exist_ok=True)
    t_pipeline_start = time.monotonic()
    print(f"[pipeline] starting — FULL_RUN={FULL_RUN}  BUILD={BUILD_NAME}")

    # ── Stage 2: Sync scenarios ────────────────────────────────────────────
    print_stage_header("2", "MANAGE_SCENARIOS", "Sync scenarios.json with analyzed requirements")
    req_path = Path("requirements/analyzed_requirements.json")
    if not req_path.exists():
        print(f"[ERROR] {req_path} not found — run Stage 1 first", file=sys.stderr)
        sys.exit(1)
    requirements = json.loads(req_path.read_text(encoding="utf-8"))
    sc_path  = Path("scenarios/scenarios.json")
    existing = json.loads(sc_path.read_text(encoding="utf-8")) if sc_path.exists() else []
    scenarios = sync_scenarios(requirements, existing)
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")

    counts = {s: sum(1 for x in scenarios if x["status"] == s)
              for s in ("new", "updated", "active", "deprecated")}
    print_stage_result("2", "MANAGE_SCENARIOS", {
        "Active":     counts["active"],
        "Updated":    counts["updated"],
        "New":        counts["new"],
        "Deprecated": counts["deprecated"],
        "Total":      len(scenarios),
        "Output":     "scenarios/scenarios.json",
    })

    # ── Stage 3: Generate tests from Kane AI code exports ─────────────────
    # collect_kane_exports.py is the authoritative Stage 3 generator.
    # It reads Kane's exported Python Playwright code from each session's
    # code-export directory and assembles test_powerapps.py with real
    # executable test bodies.  Falls back to curated bodies when Kane has
    # no export for a given AC so every scenario always has an implementation.
    print_stage_header("3", "GENERATE_TESTS",
                       "Assemble Kane-exported Python Playwright tests (Stage 3a)")
    try:
        from collect_kane_exports import collect_and_assemble
        export_stats = collect_and_assemble(
            analyzed_path="requirements/analyzed_requirements.json",
            scenarios_path=str(sc_path),
            output_path="tests/playwright/test_powerapps.py",
        )
    except Exception as exc:
        print(f"[warn] collect_kane_exports failed ({exc}), falling back to template generator")
        generate_tests(scenarios)
        export_stats = {"total": sum(1 for s in scenarios if s["status"] != "deprecated"),
                        "kane_used": 0, "fallback_used": 0, "missing": 0}

    # Persist scenarios.json with function_name now set
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")

    syntax_ok = validate_generated_tests()
    if not syntax_ok:
        print("[PIPELINE] Generated test file has syntax errors — aborting", file=sys.stderr)
        sys.exit(1)

    print_stage_result("3", "GENERATE_TESTS", {
        "Tests assembled":  export_stats.get("total", 0),
        "Kane export used": export_stats.get("kane_used", 0),
        "Fallback used":    export_stats.get("fallback_used", 0),
        "Syntax":           "VALID",
        "Output":           "tests/playwright/test_powerapps.py",
    })

    # ── Stage 4: Write test selection ──────────────────────────────────────
    print_stage_header("4", "SELECT_TESTS", f"Build test manifest ({'full' if FULL_RUN else 'incremental'} run)")
    selected = write_test_selection(scenarios)
    excluded = [s for s in scenarios if s["status"] == "deprecated"]
    run_type = "full" if FULL_RUN else "incremental"

    print_stage_result("4", "SELECT_TESTS", {
        "Run type":  run_type,
        "Selected":  f"{len(selected)} scenarios ({len(selected)} test nodes)",
        "Excluded":  f"{len(excluded)} (deprecated)",
        "Output":    "reports/pytest_selection.txt, reports/test_execution_manifest.json",
    })

    # ── Stage 5: Run HyperExecute ──────────────────────────────────────────
    print_stage_header("5", "HYPEREXECUTE", "Submit tests to LambdaTest HyperExecute")
    t5_start = time.monotonic()
    job_id = run_hyperexecute()
    t5_elapsed = round(time.monotonic() - t5_start, 1)

    he_link = (
        f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}"
        if job_id else "N/A (skipped)"
    )
    print_stage_result("5", "HYPEREXECUTE", {
        "Job ID":       job_id or "N/A",
        "Concurrency":  "5 VMs",
        "Tests":        f"{len(selected)} submitted",
        "Duration":     f"{t5_elapsed}s",
        "Dashboard":    he_link,
    }, success=bool(job_id) or not LT_USERNAME)

    # ── Stage 6: Fetch MCP results ─────────────────────────────────────────
    print_stage_header("6", "FETCH_RESULTS", "Fetch session results via MCP + LambdaTest API")
    await fetch_and_save_mcp_results(job_id)

    api_details = json.loads(Path("reports/api_details.json").read_text(encoding="utf-8"))
    session_count = len(api_details.get("he_tasks", []))
    print_stage_result("6", "FETCH_RESULTS", {
        "Sessions found": session_count,
        "Job status":     api_details.get("he_summary", {}).get("status", "unknown"),
        "Output":         "reports/api_details.json",
    })

    # ── Stage 7: Post-pipeline (normalize → validate → traceability → release → summary)
    print_stage_header("7", "POST_PIPELINE", "Normalize artifacts, build traceability, generate verdict")
    post_pipeline()

    total_elapsed = round(time.monotonic() - t_pipeline_start, 1)
    print_stage_result("7", "POST_PIPELINE", {
        "Scripts run":     f"{len(_CRITICAL_SCRIPTS)} critical + {len(_ADVISORY_SCRIPTS)} advisory",
        "Total duration":  f"{total_elapsed}s",
        "Traceability":    "reports/traceability_matrix.{md,json}",
        "Verdict":         "reports/release_recommendation.md",
        "Summary":         "GitHub Actions Step Summary",
    })

    print(f"\n[pipeline] complete — total elapsed {total_elapsed}s")


if __name__ == "__main__":
    asyncio.run(main())
