#!/usr/bin/env python3
"""
Agentic STLC Orchestrator — Stages 2-7.
Fully deterministic: no LLM required.
"""
import asyncio
import json
import os
import py_compile
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
from mcp import ClientSession
from mcp.client.sse import sse_client

sys.path.insert(0, str(Path(__file__).parent))
from stage_utils import print_stage_header, print_stage_result

# ── Runtime config ─────────────────────────────────────────────────────────
MCP_URL           = "https://mcp.lambdatest.com/mcp"
LT_API_BASE       = "https://api.lambdatest.com/automation/api/v1"
LT_USERNAME       = os.environ.get("LT_USERNAME", "")
LT_ACCESS_KEY     = os.environ.get("LT_ACCESS_KEY", "")
FULL_RUN          = os.environ.get("FULL_RUN", "true").lower() == "true"
TARGET_URL        = os.environ.get("TARGET_URL", "https://nosecretformula.vercel.app/")
TODAY             = datetime.now(timezone.utc).date().isoformat()
RUN_NUMBER        = os.environ.get("GITHUB_RUN_NUMBER", "")
BUILD_NAME        = (
    f"Agentic STLC #{RUN_NUMBER} | {TODAY}" if RUN_NUMBER
    else f"Agentic STLC | {TODAY}"
)

JOB_ID_RE = re.compile(r"jobId=([\w-]+)")
_TERMINAL_HE_STATUSES = {"completed", "passed", "failed", "error", "aborted", "cancelled"}

# Extended patterns to extract job ID from varied HE CLI output formats
_JOB_ID_PATTERNS = [
    re.compile(r"jobId=([\w-]+)"),
    re.compile(r"job[_\s-]?id[:\s=]+([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})", re.IGNORECASE),
    re.compile(r"hyperexecute/task\?jobId=([\w-]+)", re.IGNORECASE),
    re.compile(r"Job\s+(?:ID|Id|id)[:\s]+([0-9a-f]{8}-[0-9a-f]{4}-[\w-]+)", re.IGNORECASE),
]

# Enterprise-normalized status map: raw HE API value → deterministic label
_HE_STATUS_NORMALIZE: dict[str, str] = {
    "completed":  "PASSED",
    "passed":     "PASSED",
    "failed":     "FAILED",
    "error":      "INFRA_FAILURE",
    "aborted":    "CANCELLED",
    "cancelled":  "CANCELLED",
    "running":    "RUNNING",
    "initiated":  "RUNNING",
    "queued":     "RUNNING",
    "unknown":    "",          # resolved dynamically from tasks
    "":           "",
}


def _extract_job_id(text: str) -> str:
    """Try multiple regex patterns to extract HE job ID from CLI output."""
    for pattern in _JOB_ID_PATTERNS:
        m = pattern.search(text)
        if m:
            return m.group(1)
    return ""


def _derive_status_from_tasks(he_tasks: list) -> str:
    """
    When the HE job API is unreachable, derive a terminal status from
    individual task results.  Returns a raw HE-compatible status string
    so the rest of the pipeline remains unchanged.
    """
    if not he_tasks:
        return ""
    statuses = [t.get("status", "") for t in he_tasks]
    terminal = [s for s in statuses if s in ("passed", "failed")]
    if not terminal:
        return ""
    if all(s == "passed" for s in terminal):
        return "completed"
    return "failed"


def _normalize_he_status(raw_status: str, he_tasks: list) -> str:
    """
    Map a raw HE status (or a task-derived status) to an enterprise-grade
    deterministic label.  Never returns 'unknown'.
    """
    normalized = _HE_STATUS_NORMALIZE.get((raw_status or "").lower())
    if normalized:
        return normalized
    # Derive from task results when raw status is ambiguous/empty
    if he_tasks:
        task_statuses = [t.get("status", "") for t in he_tasks]
        passed = sum(1 for s in task_statuses if s == "passed")
        failed = sum(1 for s in task_statuses if s == "failed")
        total  = passed + failed
        if total == 0:
            return "NOT_EXECUTED"
        if failed == 0:
            return "PASSED"
        if passed == 0:
            return "FAILED"
        return "PARTIAL"
    return "NOT_EXECUTED" if not raw_status else "INFRA_FAILURE"

# ── Deterministic test generation ──────────────────────────────────────────
def _derive_fn_name(sc_id: str, title: str) -> str:
    """Derive a stable pytest function name from scenario ID + title.

    Must match collect_kane_exports._make_fn_name exactly — those two
    functions co-determine pytest_selection.txt and test_powerapps.py's
    actual function names. Length mismatch causes HE to request a function
    by a different name than what was generated → silent data_unavailable.
    """
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:60]
    return f"test_{sc_id.lower().replace('-', '_')}_{slug}"

TEST_HEADER = '''\
"""
Playwright test suite for LambdaTest Ecommerce Playground — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from playwright.sync_api import expect

'''

# Optional per-SC Playwright body overrides — used by collect_kane_exports.py
# only when Kane has no --code-export for that scenario. Empty for the
# TaskFlow AUT — the replay-first model means Kane always exports on
# record/replay, so this dict is dead-code unless an export pipeline failure
# falls all the way through to _FALLBACK_BODY in collect_kane_exports.py.
PLAYWRIGHT_BODIES: dict[str, str] = {}

_FALLBACK_BODY = '''\
    page.goto("{url}")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    assert page.title().strip() != "", "Page failed to load"'''


def _build_test_function(scenario: dict) -> str:
    sc_id   = scenario["id"]
    fn_name = scenario.get("function_name") or _derive_fn_name(sc_id, scenario.get("title", sc_id))
    title   = scenario.get("title", sc_id).replace('"', "'")
    url     = scenario.get("kane_url", TARGET_URL)
    body    = PLAYWRIGHT_BODIES.get(sc_id, _FALLBACK_BODY).format(url=url)
    req_id  = scenario.get("requirement_id", "AC-000")
    return (
        f'@pytest.mark.scenario("{sc_id}")\n'
        f'@pytest.mark.requirement("{req_id}")\n'
        f'def {fn_name}(page):\n'
        f'    """{sc_id}: {title}."""\n'
        f'{body}\n'
    )


# ── Stage 2: Sync scenarios (deterministic diff) ───────────────────────────
def _asset_drifted(scenario: dict) -> bool:
    """Ingested scenario: True when the asset body hash (sha256[:12] of the
    whitespace-normalized _test.md) differs from the sidecar
    `<asset>.meta.json` description_hash. Same rule as manage_scenarios.py
    and skills/scenario_generation.py. Missing asset/sidecar → not drifted."""
    from project_config import scenario_asset_path
    path = scenario_asset_path(scenario)
    if path is None or not path.exists():
        return False
    try:
        import replay_policy as _rp
        recorded = _rp.read_asset_hash(path)
        hasher = getattr(_rp, "hash_asset_body", None)
    except ImportError:
        recorded, hasher = None, None
        sidecar = path.with_suffix(".meta.json")
        if sidecar.exists():
            try:
                v = json.loads(sidecar.read_text(encoding="utf-8")).get("description_hash")
                recorded = v if isinstance(v, str) and v else None
            except (OSError, json.JSONDecodeError, AttributeError):
                recorded = None
    if not recorded:
        return False
    if hasher is None:
        import hashlib

        def hasher(text: str) -> str:  # local fallback, mirrors replay_policy.hash_asset_body
            lines = [ln.rstrip() for ln in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
            return hashlib.sha256("\n".join(lines).strip().encode("utf-8")).hexdigest()[:12]
    try:
        return hasher(path.read_text(encoding="utf-8")) != recorded
    except OSError:
        return False


def sync_scenarios(requirements: list, existing: list) -> list:
    """Many-to-one sync (docs/MANY_TO_ONE.md): requirement_id → [scenario, ...].
    Every existing record is kept (never dropped, never renumbered).
    Ingested scenarios: active, or updated when the asset drifted from its
    sidecar. Generated: source_description comparison. Zero scenarios → one
    generated scenario only when scenarios.auto_create is true."""
    from project_config import auto_create_scenarios, group_scenarios_by_requirement, is_ingested

    grouped = group_scenarios_by_requirement(existing, include_deprecated=True)
    current_req_ids = {r["id"] for r in requirements}
    auto_create = auto_create_scenarios()

    max_num = 0
    for sc in existing:
        m = re.match(r"SC-(\d+)", sc.get("id", ""))
        if m:
            max_num = max(max_num, int(m.group(1)))
    next_num = max_num + 1

    result = []
    for req in requirements:
        brd_ref = req.get("brd_ref")
        group = grouped.get(req["id"], [])
        if not group:
            if not auto_create:
                print(f"[stage2] {req['id']}: no scenarios and scenarios.auto_create=false — left uncovered")
                continue
            group = [None]  # allocate exactly one generated scenario, as before

        for existing_sc in group:
            if existing_sc is not None and is_ingested(existing_sc):
                # Ingested: the asset is authoritative — keep the record verbatim,
                # only refresh status / verification metadata.
                if existing_sc.get("status") == "deprecated":
                    status = "deprecated"
                else:
                    status = "updated" if _asset_drifted(existing_sc) else "active"
                record = {**existing_sc, "status": status, "last_verified": TODAY}
                if brd_ref and not record.get("brd_ref"):
                    record["brd_ref"] = brd_ref
                result.append(record)
                continue

            if existing_sc is None:
                sc_id  = f"SC-{next_num:03d}"
                tc_id  = f"TC-{next_num:03d}"
                next_num += 1
                status = "new"
            else:
                sc_id  = existing_sc["id"]
                tc_id  = existing_sc.get("test_case_id", sc_id.replace("SC-", "TC-"))
                # "deprecated" is a tombstone — once release_diff marks an
                # AC as removed (e.g. v1.1.0's "User can delete a task"), the
                # status must survive even though the AC line is still present
                # in taskflow.txt. Otherwise Stage 4 re-includes the test, HE
                # runs it against an AUT that no longer supports the feature,
                # and the verdict flips from GREEN to YELLOW on every run.
                if existing_sc.get("status") == "deprecated":
                    status = "deprecated"
                else:
                    status = (
                        "updated" if existing_sc.get("source_description") != req["description"]
                        else "active"
                    )

            title = req.get("kane_one_liner") or req.get("title", req["id"])
            # Fix None-fallthrough: existing_sc may carry function_name=None from
            # an earlier broken run. Always derive when missing rather than
            # propagating None into pytest_selection.txt.
            fn_name = (
                (existing_sc.get("function_name") if existing_sc else None)
                or _derive_fn_name(sc_id, title)
            )
            # Preserve any custom kane_objective the operator (or release_diff)
            # set on an existing scenario. Multi-step objectives like SC-002's
            # setup → verify lifecycle are hand-authored and would be silently
            # destroyed if we always defaulted to the AC description.
            kane_objective = (
                (existing_sc or {}).get("kane_objective")
                or f"On {TARGET_URL} — {req['description']}"
            )
            record = {
                "id":                 sc_id,
                "test_case_id":       tc_id,
                "requirement_id":     req["id"],
                "title":              title,
                "function_name":      fn_name,
                "status":             status,
                "source_description": req["description"],
                "steps":              req.get("kane_steps") or [
                    f"Navigate to {TARGET_URL}", "Verify the acceptance criterion"
                ],
                "expected_result":    req.get("kane_summary") or req["description"],
                "kane_url":           TARGET_URL,
                "kane_objective":     kane_objective,
                "last_verified":      TODAY,
            }
            # brd_ref: from the requirement (new + backfill), else whatever the record had.
            if brd_ref:
                record["brd_ref"] = (existing_sc or {}).get("brd_ref") or brd_ref
            elif (existing_sc or {}).get("brd_ref"):
                record["brd_ref"] = existing_sc["brd_ref"]
            # Preserve release-diff tombstone / review metadata (deprecated_in_release,
            # deprecated_at, review_required …) so the coverage report can attribute
            # the removal to the right release. Without this, SC-005's "removed in
            # v1.1.0" provenance is lost every time Stage 2 re-runs.
            if existing_sc:
                for k in ("feature", "deprecated_in_release", "deprecated_at", "deprecated_by",
                          "review_required", "review_reason"):
                    if existing_sc.get(k):
                        record[k] = existing_sc[k]
            result.append(record)

    # Preserve deprecated entries for removed requirements
    for sc in existing:
        if sc["requirement_id"] not in current_req_ids:
            deprecated = {**sc, "status": "deprecated"}
            if "function_name" not in deprecated:
                deprecated["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
            result.append(deprecated)

    return result


# ── Stage 3: Generate tests ─────────────────────────────────────────────────
def generate_tests(scenarios: list) -> None:
    active = [s for s in scenarios if s["status"] != "deprecated"]
    lines  = [TEST_HEADER.rstrip(), ""]
    objectives = []
    for sc in active:
        lines.append(_build_test_function(sc).rstrip())
        lines.append("")
        objectives.append({
            "scenario_id": sc["id"],
            "test_case_id": sc.get("test_case_id", ""),
            "objective": sc.get("title", sc["id"]),
        })

    out = Path("tests/playwright/test_powerapps.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    # Ensure function_name is set on each active scenario (for downstream scripts)
    for sc in active:
        if not sc.get("function_name"):
            sc["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))

    Path("kane").mkdir(exist_ok=True)
    Path("kane/objectives.json").write_text(json.dumps(objectives, indent=2), encoding="utf-8")
    print(f"[generate_tests] wrote {len(active)} test(s)")


def validate_generated_tests(test_file: str = "tests/playwright/test_powerapps.py") -> bool:
    """Validate generated Playwright test file has valid Python syntax."""
    try:
        py_compile.compile(test_file, doraise=True)
        print(f"[validate_tests] {test_file} — syntax OK")
        return True
    except py_compile.PyCompileError as e:
        print(f"[validate_tests] SYNTAX ERROR in {test_file}: {e}", file=sys.stderr)
        return False


# ── Stage 4: Write test selection ──────────────────────────────────────────
def write_test_selection(scenarios: list) -> list:
    if FULL_RUN:
        selected = [s for s in scenarios if s["status"] != "deprecated"]
    else:
        selected = [s for s in scenarios if s["status"] in ("new", "updated")]

    lines = []
    native_ids = []
    for sc in selected:
        # Many-to-one / ingested: testmu-SDK exports run natively as a directory
        # task (ci/run_selected.py → tests/playwright/native/run_with_junit.py),
        # not as a pytest node inside test_powerapps.py.
        if sc.get("export_kind") == "testmu" or sc.get("playwright_export"):
            lines.append(f"tests/playwright/native/{sc['id'].lower().replace('-', '_')}")
            native_ids.append(sc["id"])
            continue
        fn = sc.get("function_name") or _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
        lines.append(f"tests/playwright/test_powerapps.py::{fn}")

    Path("reports").mkdir(exist_ok=True)
    Path("reports/pytest_selection.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    run_type = "full" if FULL_RUN else "incremental"
    manifest = {
        "selected_scenarios": [s["id"] for s in selected],
        "selected_native": native_ids,
        "run_type": run_type,
    }
    Path("reports/test_execution_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"[test_selection] {len(lines)} test(s) — {run_type} run")
    return selected


def validate_test_selection(selection_file: str = "reports/pytest_selection.txt") -> bool:
    """Validate test selection file exists and is non-empty."""
    p = Path(selection_file)
    if not p.exists():
        print(f"[validate_selection] {selection_file} does not exist", file=sys.stderr)
        return False
    lines = [l.strip() for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]
    if not lines:
        print(f"[validate_selection] {selection_file} is empty — no tests to run", file=sys.stderr)
        return False
    print(f"[validate_selection] {len(lines)} test node(s) queued")
    return True


# ── Stage 5: Run HyperExecute ──────────────────────────────────────────────
def run_hyperexecute() -> str:
    # On Windows the binary ships as hyperexecute.exe; on Linux it has no extension.
    cli_name = "hyperexecute.exe" if sys.platform == "win32" else "hyperexecute"
    cwd = Path(".").resolve()
    cli_path = cwd / cli_name
    cli = str(cli_path) if sys.platform == "win32" else f"./{cli_name}"
    print(f"[hyperexecute] cwd={cwd}  platform={sys.platform}  binary_exists={cli_path.exists()}")

    if not cli_path.exists():
        print("[hyperexecute] binary not found — skipping HyperExecute stage")
        return ""

    if not LT_USERNAME or not LT_ACCESS_KEY:
        print("[hyperexecute] LT credentials missing — skipping HyperExecute stage")
        return ""

    # Validate test selection before submitting
    if not validate_test_selection():
        print("[hyperexecute] aborting — no tests to run")
        return ""

    sel_path = Path("reports/pytest_selection.txt")
    lines = [l.strip() for l in sel_path.read_text().splitlines() if l.strip()]
    print(f"[hyperexecute] submitting {len(lines)} test(s):")
    for line in lines:
        print(f"  {line}")

    cmd = [cli, "--user", LT_USERNAME, "--key", LT_ACCESS_KEY, "--config", "hyperexecute.yaml"]
    print(f"[hyperexecute] starting — cmd: {' '.join(cmd[:3])} ...")
    t0 = time.monotonic()
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=1800, encoding="utf-8", errors="replace")
    elapsed = round(time.monotonic() - t0, 1)
    combined = result.stdout + result.stderr

    Path("reports").mkdir(exist_ok=True)
    Path("reports/hyperexecute-cli.log").write_text(combined, encoding="utf-8")
    print(f"[hyperexecute] exit_code={result.returncode}  duration={elapsed}s  output_lines={len(combined.splitlines())}")
    if combined.strip():
        for line in combined.splitlines()[:30]:
            print(f"  {line}")

    job_id = _extract_job_id(combined)
    print(f"[hyperexecute] job_id={job_id!r}  (extracted via multi-pattern parser)")
    if not job_id:
        print("[hyperexecute] WARNING: could not extract job_id from CLI output — status resolution will use task-derived fallback")
    return job_id


# ── Stage 6: Fetch results ────────────────────────────────────────────────

# MCP responses wrap JSON in a markdown code block: ```json\n{...}\n```
_JSON_BLOCK_RE = re.compile(r"```json\s*([\s\S]*?)\s*```")


def _parse_mcp_text(text: str) -> object:
    """Parse JSON from an MCP response, stripping any markdown code fence."""
    m = _JSON_BLOCK_RE.search(text)
    candidate = m.group(1) if m else text.strip()
    return json.loads(candidate)


def _parse_session(s: dict, source: str) -> dict:
    """Normalise a session record from either the HE API or the Automation API."""
    raw_name = (
        s.get("scenario_name") or s.get("name") or s.get("session_name", "")
    )
    # conftest names sessions "SC-001 | TC-001 | test_sc_001_..." — extract fn name
    parts   = [p.strip() for p in raw_name.split("|")]
    fn_name = parts[-1] if len(parts) > 1 else raw_name
    test_id = s.get("testID") or s.get("test_id") or s.get("session_id", "")
    task_id = s.get("taskID") or s.get("task_id", "")
    status_raw = s.get("status") or s.get("status_ind", "unknown")
    status = "passed" if status_raw in ("passed", "pass", "completed") else (
        "failed" if status_raw in ("failed", "fail", "error") else status_raw
    )
    link = (
        f"https://automation.lambdatest.com/test?testID={test_id}"
        if test_id else ""
    )
    print(f"  [{source}] {fn_name!r} → {status}  testID={test_id}")
    return {"name": fn_name, "task_id": task_id, "status": status, "session_link": link}


async def _fetch_he_sessions_api(client: httpx.AsyncClient, job_id: str) -> list:
    """Try HyperExecute /v2.0/job/{id}/sessions endpoint."""
    tasks = []
    cursor = None
    page = 0
    while True:
        params: dict = {"limit": 20}
        if cursor:
            params["cursor"] = cursor
        resp = await client.get(
            f"https://api.hyperexecute.cloud/v2.0/job/{job_id}/sessions",
            params=params,
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[he_sessions_api] {resp.status_code} — {resp.text[:200]}")
            return []
        data = resp.json()
        page_sessions = data.get("data", [])
        print(f"[he_sessions_api] page {page}: {len(page_sessions)} session(s)")
        tasks.extend(_parse_session(s, "he_api") for s in page_sessions)
        metadata = data.get("metadata", {})
        if not metadata.get("hasmore"):
            break
        cursor = metadata.get("cursor")
        if not cursor:
            break
        page += 1
    return tasks


async def _fetch_automation_sessions_by_build(client: httpx.AsyncClient, build_name: str) -> list:
    """
    Fall back to LambdaTest Automation API: find the build by name and return its sessions.
    conftest.py sets build=BUILD_NAME, so the build should be searchable by that exact name.
    """
    build_id = None
    for search in (build_name, "Agentic STLC"):
        resp = await client.get(
            f"{LT_API_BASE}/builds",
            params={"s": search, "limit": 5, "sort": "desc"},
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[automation] builds search {resp.status_code}")
            continue
        builds = resp.json().get("data", [])
        print(f"[automation] {len(builds)} build(s) for search={search!r}")
        for b in builds:
            name = b.get("name", "")
            if build_name in name or search == "Agentic STLC":
                build_id = b.get("build_id")
                print(f"[automation] matched build_id={build_id!r} name={name!r}")
                break
        if build_id:
            break

    if not build_id:
        print("[automation] no matching build found")
        return []

    resp = await client.get(
        f"{LT_API_BASE}/sessions",
        params={"build_id": build_id, "limit": 50},
        auth=(LT_USERNAME, LT_ACCESS_KEY),
    )
    if resp.status_code != 200:
        print(f"[automation] sessions {resp.status_code}")
        return []
    sessions = resp.json().get("data", [])
    print(f"[automation] {len(sessions)} session(s) for build_id={build_id}")
    return [_parse_session(s, "automation") for s in sessions]


async def _fetch_he_job_status_rest(client: httpx.AsyncClient, job_id: str) -> dict:
    """
    Direct HyperExecute REST API call to retrieve job status.
    Used as a fallback when MCP is unreachable.
    Returns a job_inner dict compatible with _write_api_details expectations.
    """
    if not job_id or not LT_USERNAME or not LT_ACCESS_KEY:
        return {}
    try:
        resp = await client.get(
            f"https://api.hyperexecute.cloud/v2.0/job/{job_id}",
            auth=(LT_USERNAME, LT_ACCESS_KEY),
            timeout=15,
        )
        if resp.status_code == 200:
            data = resp.json()
            job_inner = data.get("data") or data.get("jobInfo") or data
            status = job_inner.get("status", "")
            print(f"[he_rest] job status from REST API: {status!r}  job_id={job_id}")
            return job_inner
        print(f"[he_rest] REST API returned HTTP {resp.status_code} for job_id={job_id}")
    except Exception as exc:
        print(f"[he_rest] REST API call failed: {exc}")
    return {}


async def _fetch_he_sessions(job_id: str) -> list:
    """
    Fetch per-test session results.
    Strategy 1: HyperExecute /v2.0/job/{id}/sessions  (direct, by job_id)
    Strategy 2: LambdaTest Automation API /builds + /sessions (by build name)
    """
    async with httpx.AsyncClient(timeout=30) as client:
        tasks = []
        if job_id:
            try:
                tasks = await _fetch_he_sessions_api(client, job_id)
            except Exception as exc:
                print(f"[he_sessions_api] error: {exc}")

        if not tasks:
            print(f"[he_sessions] HE API returned 0 — trying Automation API (build={BUILD_NAME!r})")
            try:
                tasks = await _fetch_automation_sessions_by_build(client, BUILD_NAME)
            except Exception as exc:
                print(f"[automation] error: {exc}")

    print(f"[he_sessions] final: {len(tasks)} session(s)")
    return tasks


async def fetch_and_save_mcp_results(job_id: str) -> None:
    if not job_id:
        print("[mcp] no job_id — writing empty api_details.json")
        _write_api_details({}, [], job_id)
        return

    mcp_url_auth = f"{MCP_URL}?username={LT_USERNAME}&accessKey={LT_ACCESS_KEY}"
    headers = {"x-lt-username": LT_USERNAME, "x-lt-access-key": LT_ACCESS_KEY}

    try:
        async with sse_client(mcp_url_auth, headers=headers) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()

                # Poll until job reaches a terminal status (max 15 min)
                job_data: dict = {}
                job_inner: dict = {}
                for attempt in range(30):
                    raw = await session.call_tool("getHyperExecuteJobInfo", {"jobId": job_id})
                    text = raw.content[0].text if raw.content else "{}"
                    try:
                        job_data  = _parse_mcp_text(text)
                        job_inner = job_data.get("jobInfo") or job_data.get("data") or job_data
                    except (json.JSONDecodeError, AttributeError):
                        job_inner = {}
                    status = job_inner.get("status", "unknown")
                    print(f"[mcp] attempt {attempt+1}/30 — job status: {status}")
                    if status in _TERMINAL_HE_STATUSES:
                        print(f"[mcp] terminal status reached: {status}")
                        break
                    if status not in ("running", "initiated", "queued"):
                        print(f"[mcp] unknown status '{status}' — stopping poll")
                        break
                    await asyncio.sleep(30)

                he_tasks = await _fetch_he_sessions(job_id)
                _write_api_details(job_inner, he_tasks, job_id)

    except Exception as exc:
        print(f"[mcp] connection failed: {exc} — falling back to HE REST API + sessions API")
        async with httpx.AsyncClient(timeout=30) as _fb_client:
            job_inner_fb = await _fetch_he_job_status_rest(_fb_client, job_id) if job_id else {}
        he_tasks = await _fetch_he_sessions(job_id)
        _write_api_details(job_inner_fb, he_tasks, job_id)


def _write_api_details(job_inner: dict, he_tasks: list, job_id: str) -> None:
    raw_status = (job_inner.get("status") or "").strip()

    # When the job API is unavailable or returns "unknown", derive from task results
    # so the report never shows an unresolvable status.
    if not raw_status or raw_status == "unknown":
        derived = _derive_status_from_tasks(he_tasks)
        if derived:
            print(f"[api_details] raw status={raw_status!r} — derived '{derived}' from {len(he_tasks)} task result(s)")
            raw_status = derived
            parser_status = "derived_from_tasks"
        else:
            parser_status = "not_executed" if not job_id else "mcp_unavailable"
    else:
        parser_status = "api_ok"

    normalized_status = _normalize_he_status(raw_status, he_tasks)

    task_pass  = sum(1 for t in he_tasks if t.get("status") == "passed")
    task_fail  = sum(1 for t in he_tasks if t.get("status") == "failed")
    task_other = len(he_tasks) - task_pass - task_fail

    he_summary = {
        "job_id":                job_inner.get("jobId") or job_id,
        "job_link":              job_inner.get("jobLink") or (
            f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}" if job_id else ""
        ),
        "status":                raw_status or "NOT_EXECUTED",
        "normalized_status":     normalized_status,
        "parser_status":         parser_status,
        "total_tasks":           job_inner.get("totalTasks") or len(he_tasks),
        "task_pass_count":       task_pass,
        "task_fail_count":       task_fail,
        "task_other_count":      task_other,
        "selenium_reports_link": job_inner.get("seleniumReportsLink", ""),
        "runtime_logs_link":     job_inner.get("runtimeLogsLink", ""),
    }
    api_details = {"he_summary": he_summary, "he_tasks": he_tasks, "kane_sessions": []}
    Path("reports").mkdir(exist_ok=True)
    Path("reports/api_details.json").write_text(
        json.dumps(api_details, indent=2), encoding="utf-8"
    )
    print(
        f"[api_details] saved {len(he_tasks)} task(s) — "
        f"raw={raw_status!r}  normalized={normalized_status}  parser={parser_status}"
        f"  pass={task_pass} fail={task_fail}"
    )


# ── Stage 7: Release recommendation (threshold-based) ─────────────────────
def _dedup_tasks(he_tasks: list) -> list:
    """Deduplicate by test name, keeping the first occurrence (LT API returns newest first)."""
    seen: dict = {}
    for t in he_tasks:
        key = t.get("name") or t.get("task_id", "")
        seen.setdefault(key, t)
    return list(seen.values())


def write_recommendation(he_tasks: list, requirements_total: int) -> None:
    he_tasks = _dedup_tasks(he_tasks)
    total  = len(he_tasks)
    passed = sum(1 for t in he_tasks if t["status"] == "passed")
    failed = total - passed
    pass_rate = round(passed / total * 100, 1) if total > 0 else 0.0

    if total == 0:
        verdict = "YELLOW"
        rec = "Test results not yet available — manual review required before release."
    elif pass_rate >= 80:
        verdict = "GREEN"
        rec = f"Approve release — {passed}/{total} tests passed ({pass_rate}%)."
    elif pass_rate >= 60:
        verdict = "YELLOW"
        rec = f"Conditional release — {failed} test(s) failed. Review failures before proceeding."
    else:
        verdict = "RED"
        rec = f"Block release — pass rate is {pass_rate}% ({failed} failed). Investigate failures."

    failing_lines = (
        "- None" if failed == 0
        else "\n".join(
            f"- {t['name'] or t['task_id']}"
            for t in he_tasks if t["status"] != "passed"
        )
    )

    content = f"""# QA Release Recommendation
**Verdict:** {verdict}
## Summary
- Requirements covered: {requirements_total}/{requirements_total}
- Scenarios executed: {total}
- Pass rate: {pass_rate}% ({passed} passed, {failed} failed)
## Failing Scenarios
{failing_lines}
## Recommendation
{rec}
"""
    Path("reports/release_recommendation.md").write_text(content, encoding="utf-8")
    print(f"[recommendation] Verdict: {verdict}  pass_rate={pass_rate}%")


# ── Post-pipeline: deterministic CI report scripts ─────────────────────────
# Critical scripts must all succeed — pipeline exits 1 if any fail.
# Order matters: normalize → traceability → coverage → gates → rca → summary
_CRITICAL_SCRIPTS = [
    # Stage 6b — native (testmu) tasks write per-scenario results on the HE VM;
    # pull the merged TestReports artefact into reports/ before normalizing.
    "ci/fetch_he_artifacts.py",
    "ci/normalize_artifacts.py",
    # Stage 2b — confidence scoring runs before traceability so its outputs
    # (high_risk_requirements.json, scenario-confidence-report.json) are
    # available to release_recommendation and write_github_summary.
    "ci/scenario_confidence.py",
    "ci/build_traceability.py",
    "ci/release_recommendation.py",
    "ci/coverage_analysis.py",
    "ci/write_github_summary.py",
]
# Advisory scripts log warnings but never block the pipeline.
# Order matters: fetch_rca must run before failure_intelligence (reads rca_report.json),
# and failure_intelligence must run before self_healing (reads failure_intelligence.json).
_ADVISORY_SCRIPTS = [
    # Stage 0 — Agentic Release Notes diff (preview only by default).
    # Runs unconditionally; if there's no release_notes/*.md it exits 1
    # which the advisory chain logs as a warning and moves on.
    "ci/release_diff.py",
    "ci/impact_analysis.py",
    "ci/quality_gates.py",
    "ci/fetch_rca.py",
    "ci/failure_intelligence.py",
    "ci/self_healing.py",
    "ci/validate_report.py",
    "ci/pipeline_metrics.py",
]


def post_pipeline() -> None:
    """Run post-pipeline scripts. Exits non-zero if any critical script fails."""
    failed_critical = []

    # write_github_summary.py only persists output when GITHUB_STEP_SUMMARY is
    # set (CI gives us this for free). Locally it streams to stdout, leaving
    # any stale reports/pipeline_summary.md behind. Pre-seed the env var so
    # local runs also produce a fresh pipeline_summary.md.
    summary_path = Path("reports/pipeline_summary.md")
    summary_path.unlink(missing_ok=True)
    if "GITHUB_STEP_SUMMARY" not in os.environ:
        os.environ["GITHUB_STEP_SUMMARY"] = str(summary_path)

    for script in _CRITICAL_SCRIPTS:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout.strip())
        if result.returncode != 0:
            print(f"[ERROR] Critical script failed: {script} (exit {result.returncode})", file=sys.stderr)
            if result.stderr:
                print(result.stderr[:800], file=sys.stderr)
            failed_critical.append(script)
        else:
            print(f"[post-pipeline] {script} ok")

    for script in _ADVISORY_SCRIPTS:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout.strip())
        if result.returncode != 0:
            print(f"[warn] Advisory script failed: {script} (exit {result.returncode})")
            if result.stderr:
                print(result.stderr[:400])
        else:
            print(f"[post-pipeline] {script} ok")

    if failed_critical:
        print(
            f"\n[PIPELINE] {len(failed_critical)} critical script(s) failed: "
            + ", ".join(failed_critical),
            file=sys.stderr,
        )
        sys.exit(1)


# ── Main ────────────────────────────────────────────────────────────────────
async def main() -> None:
    Path("reports").mkdir(exist_ok=True)
    t_pipeline_start = time.monotonic()
    print(f"[pipeline] starting — FULL_RUN={FULL_RUN}  BUILD={BUILD_NAME}")

    # ── Stage 2: Sync scenarios ────────────────────────────────────────────
    print_stage_header("2", "MANAGE_SCENARIOS", "Sync scenarios.json with analyzed requirements")
    req_path = Path("requirements/analyzed_requirements.json")
    if not req_path.exists():
        print(f"[ERROR] {req_path} not found — run Stage 1 first", file=sys.stderr)
        sys.exit(1)
    requirements = json.loads(req_path.read_text(encoding="utf-8"))
    sc_path  = Path("scenarios/scenarios.json")
    existing = json.loads(sc_path.read_text(encoding="utf-8")) if sc_path.exists() else []
    scenarios = sync_scenarios(requirements, existing)
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")

    counts = {s: sum(1 for x in scenarios if x["status"] == s)
              for s in ("new", "updated", "active", "deprecated")}
    # Many-to-one: requirements with no non-deprecated scenario are uncovered
    # (scenarios.auto_create=false leaves them so — reported, not filled).
    covered = {x["requirement_id"] for x in scenarios if x["status"] != "deprecated"}
    uncovered = [r["id"] for r in requirements if r["id"] not in covered]
    if uncovered:
        print(f"[stage2] uncovered requirements ({len(uncovered)}): {', '.join(uncovered)}")
    print_stage_result("2", "MANAGE_SCENARIOS", {
        "Active":     counts["active"],
        "Updated":    counts["updated"],
        "New":        counts["new"],
        "Deprecated": counts["deprecated"],
        "Uncovered":  len(uncovered),
        "Total":      len(scenarios),
        "Output":     "scenarios/scenarios.json",
    })

    # ── Stage 3: Generate tests from Kane AI code exports ─────────────────
    # collect_kane_exports.py is the authoritative Stage 3 generator.
    # It reads Kane's exported Python Playwright code from each session's
    # code-export directory and assembles test_powerapps.py with real
    # executable test bodies.  Falls back to curated bodies when Kane has
    # no export for a given AC so every scenario always has an implementation.
    print_stage_header("3", "GENERATE_TESTS",
                       "Assemble Kane-exported Python Playwright tests (Stage 3a)")
    try:
        from collect_kane_exports import collect_and_assemble
        export_stats = collect_and_assemble(
            analyzed_path="requirements/analyzed_requirements.json",
            scenarios_path=str(sc_path),
            output_path="tests/playwright/test_powerapps.py",
        )
    except Exception as exc:
        print(f"[warn] collect_kane_exports failed ({exc}), falling back to template generator")
        generate_tests(scenarios)
        export_stats = {"total": sum(1 for s in scenarios if s["status"] != "deprecated"),
                        "kane_used": 0, "fallback_used": 0, "missing": 0}

    # Persist scenarios.json with function_name now set
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")

    syntax_ok = validate_generated_tests()
    if not syntax_ok:
        print("[PIPELINE] Generated test file has syntax errors — aborting", file=sys.stderr)
        sys.exit(1)

    print_stage_result("3", "GENERATE_TESTS", {
        "Tests assembled":  export_stats.get("total", 0),
        "Kane export used": export_stats.get("kane_used", 0),
        "Fallback used":    export_stats.get("fallback_used", 0),
        "Syntax":           "VALID",
        "Output":           "tests/playwright/test_powerapps.py",
    })

    # ── Stage 4: Write test selection ──────────────────────────────────────
    print_stage_header("4", "SELECT_TESTS", f"Build test manifest ({'full' if FULL_RUN else 'incremental'} run)")
    selected = write_test_selection(scenarios)
    excluded = [s for s in scenarios if s["status"] == "deprecated"]
    run_type = "full" if FULL_RUN else "incremental"

    print_stage_result("4", "SELECT_TESTS", {
        "Run type":  run_type,
        "Selected":  f"{len(selected)} scenarios ({len(selected)} test nodes)",
        "Excluded":  f"{len(excluded)} (deprecated)",
        "Output":    "reports/pytest_selection.txt, reports/test_execution_manifest.json",
    })

    # ── Stage 5: Run HyperExecute ──────────────────────────────────────────
    print_stage_header("5", "HYPEREXECUTE", "Submit tests to LambdaTest HyperExecute")
    t5_start = time.monotonic()
    job_id = run_hyperexecute()
    t5_elapsed = round(time.monotonic() - t5_start, 1)

    he_link = (
        f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}"
        if job_id else "N/A (skipped)"
    )
    print_stage_result("5", "HYPEREXECUTE", {
        "Job ID":       job_id or "N/A",
        "Concurrency":  "5 VMs",
        "Tests":        f"{len(selected)} submitted",
        "Duration":     f"{t5_elapsed}s",
        "Dashboard":    he_link,
    }, success=bool(job_id) or not LT_USERNAME)

    # ── Stage 6: Fetch MCP results ─────────────────────────────────────────
    print_stage_header("6", "FETCH_RESULTS", "Fetch session results via MCP + LambdaTest API")
    await fetch_and_save_mcp_results(job_id)

    api_details = json.loads(Path("reports/api_details.json").read_text(encoding="utf-8"))
    session_count = len(api_details.get("he_tasks", []))
    print_stage_result("6", "FETCH_RESULTS", {
        "Sessions found": session_count,
        "Job status":     api_details.get("he_summary", {}).get("status", "unknown"),
        "Output":         "reports/api_details.json",
    })

    # ── Stage 7: Post-pipeline (normalize → validate → traceability → release → summary)
    print_stage_header("7", "POST_PIPELINE", "Normalize artifacts, build traceability, generate verdict")
    post_pipeline()

    total_elapsed = round(time.monotonic() - t_pipeline_start, 1)
    print_stage_result("7", "POST_PIPELINE", {
        "Scripts run":     f"{len(_CRITICAL_SCRIPTS)} critical + {len(_ADVISORY_SCRIPTS)} advisory",
        "Total duration":  f"{total_elapsed}s",
        "Traceability":    "reports/traceability_matrix.{md,json}",
        "Verdict":         "reports/release_recommendation.md",
        "Summary":         "GitHub Actions Step Summary",
    })

    print(f"\n[pipeline] complete — total elapsed {total_elapsed}s")


if __name__ == "__main__":
    asyncio.run(main())
